import { compileJavascript } from './compile-javascript.js';
import { removeRecognizedFiles } from './remove-recognized-files.js';
import type { FsPaths } from '$lib/fs/types.js';
import type { FetchedSchema } from '../fetch/types.js';
import type { TypeOptions } from '$lib/index.js';
import type { JavascriptCode, TypescriptCode } from './types.js';
import { getDatabaseTs } from './get-database-ts.js';
import { getSchemaTs } from './get-schema-ts.js';
import { getTypesTs } from './get-types-ts.js';
import { writeFiles } from './write-files.js';
export const generate = async (
  schema: FetchedSchema,
  typeOptions: TypeOptions,
  outputDirectory: string,
  compileJs: boolean
): Promise<FsPaths[]> => {
  await removeRecognizedFiles(outputDirectory);
  const bannerComment = `
    /**
     * Generated by Frieda on ${new Date().toUTCString()}
     * Run \`frieda g\` to re-generate.
     */
  `;

  const typescript: TypescriptCode = {
    'database.ts': getDatabaseTs(schema, bannerComment),
    'schema.ts': getSchemaTs(schema, typeOptions, bannerComment),
    'types.ts': getTypesTs(schema, typeOptions, bannerComment)
  };

  let out: TypescriptCode | JavascriptCode = typescript;
  const files = await writeFiles(out, outputDirectory);

  if (compileJs) {
    out = compileJavascript(files) as JavascriptCode;
    await removeRecognizedFiles(outputDirectory);
  }

  return await writeFiles(out, outputDirectory);
};
